AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Description: Project Name. This name will be a subdomain.
    Type: String
    Default: opendj
  OpenamStackName:
    Description: Stack name that built OpenAM by Cloudformation.
    Type: String
    Default: openam
  DeveloperCIDR:
    Description: IP range (CIDR notation) for Developer
    Type: String
    Default: 0.0.0.0/0
  InstanceType:
    Description: Instant type to build OpenDJ.
    Type: String
    Default: t2.micro
  KeyName:
    Description: Key name for connecting to OpenDJ instance.
    Type: AWS::EC2::KeyPair::KeyName
  HostedZoneName:
    Description: Hosted zone name.
    Type: String
  OpendjRpmUri:
    Description: RPM file download URI.
    Type: String
  RootPw:
    Description: OpenDJ root password.
    Type: String
  BaseDn:
    Description: OpenDJ base domain name.
    Type: String

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ['-', ['Ref':ProjectName, sg]]
      GroupDescription: OpenDJ Security Group
      VpcId:
        Fn::ImportValue:
          !Sub ${OpenamStackName}-vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref DeveloperCIDR
        - IpProtocol: tcp
          FromPort: 389
          ToPort: 389
          SourceSecurityGroupId:
            Fn::ImportValue:
              !Sub ${OpenamStackName}-security-group
      Tags:
        - Key: Name
          Value: !Join ['-', ['Ref':ProjectName, sg]]
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - opsworks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: opsworks-service
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:*'
                  - 'iam:PassRole'
                  - 'cloudwatch:GetMetricStatistics'
                  - 'elasticloadbalancing:*'
                Resource: '*'
  OpsWorksEC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref OpsWorksEC2Role
  OpsWorksStack:
    Type: AWS::OpsWorks::Stack
    Properties:
      Name: !Join ['-', ['Ref':ProjectName, stack]]
      ServiceRoleArn: !GetAtt ServiceRole.Arn
      DefaultInstanceProfileArn: !GetAtt InstanceProfile.Arn
      ConfigurationManager:
        Name: Chef
        Version: 12
      DefaultOs: Amazon Linux 2
      UseCustomCookbooks: true
      CustomCookbooksSource:
        Type: git
        Url: https://github.com/ot-nemoto/opsworks-openam-cookbooks.git
      DefaultRootDeviceType: ebs
      DefaultSshKeyName: !Ref KeyName
      VpcId:
        Fn::ImportValue:
          !Sub ${OpenamStackName}-vpc
      DefaultSubnetId:
        Fn::ImportValue:
          !Sub ${OpenamStackName}-public-subnet-2
      CustomJson:
        OPENDJ_RPM_URI: !Ref OpendjRpmUri
        ROOT_PW: !Ref RootPw
        BASE_DN: !Ref BaseDn
  OpsWorksLayer:
    Type: AWS::OpsWorks::Layer
    Properties:
      StackId: !Ref OpsWorksStack
      Type: custom
      Shortname: opendj
      CustomRecipes:
        Deploy:
        - opendj
      EnableAutoHealing: true
      AutoAssignElasticIps: true
      AutoAssignPublicIps: false
      Name: !Join ['-', ['Ref':ProjectName, layer]]
      CustomSecurityGroupIds:
        - !Ref SecurityGroup
  OpsWorksInstance:
    Type: AWS::OpsWorks::Instance
    Properties:
      StackId: !Ref OpsWorksStack
      LayerIds:
        - !Ref OpsWorksLayer
      InstanceType: !Ref InstanceType
  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Name: !Join [".", ['Ref':ProjectName, 'Ref':HostedZoneName]]
      Type: A
      TTL: 60
      ResourceRecords:
        - !GetAtt OpsWorksInstance.PublicIp

Outputs:
  PublicIp:
    Value: !GetAtt OpsWorksInstance.PublicIp
    Export:
      Name: !Join ['-', ['Fn::Sub':'${AWS::StackName}', public-ip]]
  PublicDns:
    Value: !Ref RecordSet
    Export:
      Name: !Join ['-', ['Fn::Sub':'${AWS::StackName}', public-dns]]
